AWSTemplateFormatVersion: '2010-09-09'
Description: 'S3 bucket for hosting a static website'
Resources:
  MyBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: 'frontend-btg-challenge-bucket'
      WebsiteConfiguration:
        IndexDocument: 'index.html'
        ErrorDocument: '404.html'
  BucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref MyBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Sub 'arn:aws:s3:::${MyBucket}/*'

Outputs:
  WebsiteURL:
    Value: !Sub 'http://${MyBucket}.s3-website-${AWS::Region}.amazonaws.com'
    Description: 'URL for the website hosted on S3'